spring:
  application:
    name: task-management-back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: U0VSR0lPTUFSUVVFWkRFVg==

admin:
  email: "admin@test.com"
  password: "admin"

